version: '3'

services:
  db:
    image: postgres:latest
    container_name: bot_gpt_project
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telegram_bot_db
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
    volumes:
      - ./data:/var/lib/postgresql/data
